Repository vocascan/vocascan-server, pull requests merged in 2021-11, with the labels that each got.

#63 Feature/vocascan cli
  .eslintrc.json
  .gitattributes
  .github/workflows/ci.yml
  .github/workflows/docker.yml
  .github/workflows/test.yml
  Dockerfile
  app/Controllers/InfoController.js
  app/Services/AuthServiceProvider.js
  app/config/config/index.js
  app/config/config/parsers.js
  app/config/config/schema.js
  app/utils/index.js
  cmd/admin/index.js
  cmd/admin/user.js
  cmd/generate.js
  cmd/web.js
  database/Migration.js
  database/index.js
  package-lock.json
  package.json
  scripts/jwt-secret.js
  server.js
  vocascan-server.js
Labels: kind/enhancement, kind/dependencies, kind/proposal

#66 enable logger option
  app/config/config/index.js
  app/config/config/schema.js
  app/config/logger/index.js
  vocascan.config.example.js
Labels: kind/enhancement

#64 Feature/traefik
  docker/traefik/.gitignore
  docker/traefik/docker-compose.yml
  docker/traefik/traefik.toml
  docker/traefik/traefik_dynamic.toml
  docker/traefik/vocascan.config.js
Labels: kind/enhancement, kind/docker

#62 Docs: Swagger
  docs/api/swagger.json
Labels: kind/docs

#67 Docs/Readme update
  README.md
  images/vocascan-cover.svg
Labels: kind/docs
