Repository vocascan/vocascan-server, pull requests merged in 2021-04, with the labels that each got.

#34 script to generate jwt secret
  package.json
  scripts/jwt-secret.js
Labels: kind/dependencies, kind/enhancement

#32 Error handling
  app/Controllers/AuthController.js
  app/Controllers/GroupController.js
  app/Controllers/LanguagePackageController.js
  app/Controllers/QueryController.js
  app/Controllers/StatsController.js
  app/Controllers/VocabularyController.js
  app/Middleware/ErrorMiddleware.js
  app/Middleware/ProtectMiddleware.js
  app/Services/AuthServiceProvider.js
  app/Services/GroupServiceProvider.js
  app/Services/LanguagePackageServiceProvider.js
  app/Services/QueryServiceProvider.js
  app/Services/StatsServiceProvider.js
  app/Services/VocabularyServiceProvider.js
  app/utils/ApiError.js
  app/utils/catchAsync.js
  app/utils/index.js
  package-lock.json
  package.json
  routes/api.js
  server.js
Labels: kind/enhancement, kind/improvement

#36 check if vocab can be learned due to last query date
  app/Services/QueryServiceProvider.js
  app/utils/index.js
Labels: kind/bug

#33 Search with name instead of id for user role
  app/Services/AuthServiceProvider.js
  database/migrations/0001.roles.js
  database/migrations/0002.users.js
  database/models/Role.js
  database/models/User.js
  database/seeders/0001.roles.js
  package-lock.json
  package.json
Labels: kind/bug, kind/improvement

#37 send 404 if group or package was not found
  app/Services/GroupServiceProvider.js
  app/Services/QueryServiceProvider.js
  app/Services/VocabularyServiceProvider.js
Labels: kind/bug

#38 send stats in get packages and get groups route
  app/Controllers/GroupController.js
  app/Controllers/LanguagePackageController.js
  app/Controllers/StatsController.js
  app/Services/LanguagePackageServiceProvider.js
  app/Services/QueryServiceProvider.js
  app/Services/StatsServiceProvider.js
Labels: kind/enhancement

#41 Issuetemplates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  README.md
Labels: kind/enhancement

#40 fix: docker image alpine error
  .github/workflows/docker.yml
  Dockerfile
Labels: kind/docker, kind/github-actions
