Repository vocascan/vocascan-server, pull requests merged in 2021-05, with the labels that each got.

#42 added version route
  app/Controllers/InfoController.js
  app/Services/InfoServiceProvider.js
  package.json
  routes/api.js
Labels: kind/api

#43 added group description
  app/Services/GroupServiceProvider.js
  app/Services/LanguagePackageServiceProvider.js
  database/migrations/0004.groups.js
  database/models/Group.js
Labels: kind/api, kind/sequelize

#46 validate email on register
  app/Services/AuthServiceProvider.js
Labels: kind/enhancement

#47 Password reset
  app/Controllers/AuthController.js
  app/Services/AuthServiceProvider.js
  routes/api.js
Labels: kind/api, kind/enhancement

#50 fix: 404 in user stats route if no packages found
  app/Services/StatsServiceProvider.js
Labels: kind/bug

#49 fix: not set last query in correct staged vocab
  app/Services/QueryServiceProvider.js
Labels: kind/bug

#48 Unique username
  app/Middleware/ErrorMiddleware.js
  app/Services/AuthServiceProvider.js
  app/utils/ApiError.js
  database/migrations/0002.users.js
  database/models/User.js
Labels: kind/improvement
