Repository vocascan/vocascan-server, pull requests merged in 2022-01, with the labels that each got.

#73 fix cors if cors includes *
  app/Middleware/SecurityMiddleware.js
Labels: kind/bug

#72 Feature/legal templates
  .gitignore
  app/Controllers/StaticPagesController.js
  app/config/config/schema.js
  routes/index.js
  routes/pages.js
Labels: kind/enhancement, kind/api, priority/medium

#75 Fix/traefik pathprefix
  docker/traefik/docker-compose.yml
Labels: kind/enhancement, kind/docker, priority/low

#81 closes Update Swagger Documentation for password reset #80
  docs/api/swagger.json
Labels: kind/bug

#79 Added Password Complexity to register and password reset
  app/Controllers/AuthController.js
  app/Services/AuthServiceProvider.js
  app/utils/index.js
Labels: kind/enhancement
