Repository vocascan/vocascan-server, pull requests merged in 2022-04, with the labels that each got.

#84 Improved run programmatically
  cmd/web.js
  server.js
Labels: kind/improvement

#78 Email verification
  app/Controllers/AuthController.js
  app/Controllers/InfoController.js
  app/Controllers/VerificationController.js
  app/Middleware/ProtectMiddleware.js
  app/Services/AuthServiceProvider.js
  app/Templates/mailer/accountVerification.eta
  app/Templates/mailer/layout.eta
  app/Templates/views/accountVerification.eta
  app/Templates/views/layout.eta
  app/config/config/index.js
  app/config/config/parsers.js
  app/config/config/schema.js
  app/config/joi.js
  app/config/mailer/index.js
  app/utils/constants.js
  app/utils/index.js
  database/migrations/0011.emailVerification.js
  database/models/User.js
  docs/api/swagger.json
  images/icons/error.svg
  images/icons/success.svg
  images/logo/color-rect.svg
  images/logo/color-round.svg
  images/logo/vocascan-cloud.svg
  images/logo/vocascan-logo.png
  images/logo/vocascan-round-linux.png
  images/logo/vocascan-round-mac.png
  images/logo/vocascan-round-win.ico
  package-lock.json
  package.json
  routes/api.js
  routes/pages.js
  server.js
  vocascan.config.example.js
Labels: kind/feature, kind/breaking

#85 Vocabulary-Search in group route
  .gitignore
  app/Controllers/VocabularyController.js
  app/Services/VocabularyServiceProvider.js
  docs/api/swagger.json
Labels: kind/enhancement
